# Generated by Django 4.2.2 on 2023-10-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iot_data', models.JSONField()),
            ],
            options={
                'verbose_name': 'IOTData Storage',
                'verbose_name_plural': 'IOTData Storages',
            },
        ),
    ]
