# Generated by Django 4.2.2 on 2023-10-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastorage',
            options={'verbose_name': 'Data Storage', 'verbose_name_plural': 'Data Storages'},
        ),
        migrations.AlterField(
            model_name='datastorage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
