# Generated by Django 4.2.2 on 2023-10-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_app', '0002_alter_datastorage_options_alter_datastorage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
