# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ustomer.proto\x12\tcustomers\"T\n\x15\x43reateCustomerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\")\n\x12GetCustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"i\n\x15UpdateCustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\"\\\n\x08\x43ustomer\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\",\n\x15\x44\x65leteCustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xac\x02\n\x0f\x43ustomerService\x12G\n\x0e\x43reateCustomer\x12 .customers.CreateCustomerRequest\x1a\x13.customers.Customer\x12\x41\n\x0bGetCustomer\x12\x1d.customers.GetCustomerRequest\x1a\x13.customers.Customer\x12G\n\x0eUpdateCustomer\x12 .customers.UpdateCustomerRequest\x1a\x13.customers.Customer\x12\x44\n\x0e\x44\x65leteCustomer\x12 .customers.DeleteCustomerRequest\x1a\x10.customers.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATECUSTOMERREQUEST']._serialized_start=29
  _globals['_CREATECUSTOMERREQUEST']._serialized_end=113
  _globals['_GETCUSTOMERREQUEST']._serialized_start=115
  _globals['_GETCUSTOMERREQUEST']._serialized_end=156
  _globals['_UPDATECUSTOMERREQUEST']._serialized_start=158
  _globals['_UPDATECUSTOMERREQUEST']._serialized_end=263
  _globals['_CUSTOMER']._serialized_start=265
  _globals['_CUSTOMER']._serialized_end=357
  _globals['_DELETECUSTOMERREQUEST']._serialized_start=359
  _globals['_DELETECUSTOMERREQUEST']._serialized_end=403
  _globals['_EMPTY']._serialized_start=405
  _globals['_EMPTY']._serialized_end=412
  _globals['_CUSTOMERSERVICE']._serialized_start=415
  _globals['_CUSTOMERSERVICE']._serialized_end=715
# @@protoc_insertion_point(module_scope)
