# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import customer_pb2 as customer__pb2


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCustomer = channel.unary_unary(
                '/customers.CustomerService/CreateCustomer',
                request_serializer=customer__pb2.CreateCustomerRequest.SerializeToString,
                response_deserializer=customer__pb2.Customer.FromString,
                )
        self.GetCustomer = channel.unary_unary(
                '/customers.CustomerService/GetCustomer',
                request_serializer=customer__pb2.GetCustomerRequest.SerializeToString,
                response_deserializer=customer__pb2.Customer.FromString,
                )
        self.UpdateCustomer = channel.unary_unary(
                '/customers.CustomerService/UpdateCustomer',
                request_serializer=customer__pb2.UpdateCustomerRequest.SerializeToString,
                response_deserializer=customer__pb2.Customer.FromString,
                )
        self.DeleteCustomer = channel.unary_unary(
                '/customers.CustomerService/DeleteCustomer',
                request_serializer=customer__pb2.DeleteCustomerRequest.SerializeToString,
                response_deserializer=customer__pb2.Empty.FromString,
                )


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomer,
                    request_deserializer=customer__pb2.CreateCustomerRequest.FromString,
                    response_serializer=customer__pb2.Customer.SerializeToString,
            ),
            'GetCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomer,
                    request_deserializer=customer__pb2.GetCustomerRequest.FromString,
                    response_serializer=customer__pb2.Customer.SerializeToString,
            ),
            'UpdateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomer,
                    request_deserializer=customer__pb2.UpdateCustomerRequest.FromString,
                    response_serializer=customer__pb2.Customer.SerializeToString,
            ),
            'DeleteCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomer,
                    request_deserializer=customer__pb2.DeleteCustomerRequest.FromString,
                    response_serializer=customer__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customers.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.CustomerService/CreateCustomer',
            customer__pb2.CreateCustomerRequest.SerializeToString,
            customer__pb2.Customer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.CustomerService/GetCustomer',
            customer__pb2.GetCustomerRequest.SerializeToString,
            customer__pb2.Customer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.CustomerService/UpdateCustomer',
            customer__pb2.UpdateCustomerRequest.SerializeToString,
            customer__pb2.Customer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.CustomerService/DeleteCustomer',
            customer__pb2.DeleteCustomerRequest.SerializeToString,
            customer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
